"""Stage 5: turning pair probabilities into per-entity match sets.

A plain ``p > 0.5`` rule is the wrong objective twice over. First, the metric is
precision-weighted, so the optimal operating point sits well above the
probability-calibrated one. Second, the metric is computed *per entity*, so what
matters is the shape of each entity's candidate distribution, not each pair in
isolation.

Five composable rules are therefore available, each motivated by a property of
the data:

``threshold`` / ``threshold_s2`` / ``threshold_s3``
    Absolute probability cut, optionally per source. Source 2 and Source 3 were
    generated by different noise processes, so their score distributions differ.

``rel_threshold``
    Keep a candidate only if its probability is at least this fraction of the
    entity's best candidate. Entities have at most a handful of true matches, and
    a candidate far weaker than the leader is nearly always a distractor.

``min_best``
    If the entity's best candidate is below this, predict the empty set. This is
    the explicit singleton rule: ~5.6% of entities have no true match at all, and
    each one correctly left empty is worth a full 1.0.

``max_matches``
    Hard cap on the number of accepted matches. The ground truth never exceeds 11
    matches, and 5 matches from Source 2 / 6 from Source 3.

``exclusive``
    Global conflict resolution: every matched Source-2/3 record has exactly one
    true Source-1 owner (verified across all 7,638,365 training pairs), so when
    several entities claim the same record, only the strongest claim survives.
"""
from __future__ import annotations

from dataclasses import dataclass, asdict

import polars as pl


@dataclass
class DecisionConfig:
    threshold: float = 0.5
    threshold_s2: float | None = None
    threshold_s3: float | None = None
    rel_threshold: float = 0.0
    min_best: float = 0.0
    max_matches: int = 0
    exclusive: bool = False

    def to_dict(self) -> dict:
        return asdict(self)


def apply(scored: pl.DataFrame, cfg: DecisionConfig,
          score_col: str = "p") -> pl.DataFrame:
    """Return the accepted (a_idx, b_idx) pairs under ``cfg``.

    ``scored`` must contain a_idx, b_idx, ``score_col`` and is_s3.
    """
    p = pl.col(score_col)

    if cfg.threshold_s2 is not None or cfg.threshold_s3 is not None:
        t2 = cfg.threshold if cfg.threshold_s2 is None else cfg.threshold_s2
        t3 = cfg.threshold if cfg.threshold_s3 is None else cfg.threshold_s3
        thr = pl.when(pl.col("is_s3") == 1).then(pl.lit(t3)).otherwise(pl.lit(t2))
    else:
        thr = pl.lit(cfg.threshold)

    out = scored.with_columns(_best=p.max().over("a_idx"))
    keep = p >= thr
    if cfg.rel_threshold > 0:
        keep = keep & (p >= cfg.rel_threshold * pl.col("_best"))
    if cfg.min_best > 0:
        keep = keep & (pl.col("_best") >= cfg.min_best)
    out = out.filter(keep)

    if cfg.max_matches:
        out = (out.sort(["a_idx", score_col], descending=[False, True])
                  .group_by("a_idx", maintain_order=True).head(cfg.max_matches))

    if cfg.exclusive:
        # Keep only the strongest claim on each Source-2/3 record. b_idx is used
        # as the tie-break so the result is deterministic.
        out = (out.sort([score_col, "a_idx"], descending=[True, False])
                  .unique(subset=["b_idx"], keep="first"))

    return out.select("a_idx", "b_idx")

def add_integer_keys(scored: pl.DataFrame) -> pl.DataFrame:
    """Attach compact integer keys for the decision layer's window functions.

    Factorising through two small unique tables is far cheaper than ranking the
    entity-id strings of a ~35M-row frame directly.
    """
    a_map = scored.select("a_entity_id").unique().with_row_index("a_idx")
    b_map = scored.select("b_entity_id").unique().with_row_index("b_idx")
    return (scored.join(a_map, on="a_entity_id", how="inner")
                  .join(b_map, on="b_entity_id", how="inner"))
